### ISSUE TITLE
v2.2.2: pi TUI not available — @sinclair/typebox module resolution failure

### ISSUE THREAD

**Issue by cjnova** [rcarmo/piclaw#570]
## Description

After upgrading from 2.2.0 to 2.2.2, the `pi` TUI command no longer launches. It previously worked in 2.2.0.

Running `pi` from the terminal shows extension load failures due to a missing `@sinclair/typebox` dependency:

```
[search-backend] __piclaw_registerRoute not available; running outside PiClaw.
Error: Failed to load extension "/workspace/.pi/extensions/piclaw-fleet/index.ts": Failed to load extension: ResolveMessage: Cannot find module '@sinclair/typebox' from '/workspace/.pi/extensions/piclaw-fleet/supervisor.ts'
Error: Failed to load extension "/workspace/.pi/extensions/dev-tools/index.ts": Failed to load extension: ResolveMessage: Cannot find module '@sinclair/typebox' from '/workspace/.pi/extensions/dev-tools/supervisor.ts'
Error: Failed to load extension "/workspace/.pi/extensions/delegate/index.ts": Failed to load extension: ResolveMessage: Cannot find module '@sinclair/typebox' from '/workspace/.pi/extensions/delegate/supervisor.ts'
Error: Failed to load extension "/workspace/.pi/extensions/code-validator/index.ts": Failed to load extension: ResolveMessage: Cannot find module '@sinclair/typebox' from '/workspace/.pi/extensions/code-validator/supervisor.ts'
```

After these errors, the TUI does not start — it returns to the shell prompt.

## Expected behavior

`pi` should launch the TUI as it did in v2.2.0. Extensions should resolve `@sinclair/typebox` without issues.

## Environment

- Version: 2.2.2 (regression from 2.2.0)
- Host: container (agent@cadenova-device)
